# Generated by Django 3.2.9 on 2021-11-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211115_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='user',
            name='curso',
            field=models.CharField(max_length=255, verbose_name='Curso vinculado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
