# Generated by Django 3.2.9 on 2021-11-30 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='couse',
            new_name='course',
        ),
    ]
